CREATE TABLE Store (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(99) NOT NULL,
    Email NVARCHAR(99) NOT NULL,
    Phone NVARCHAR(99) NOT NULL,
    Addess NVARCHAR(99) NOT NULL
)

CREATE TABLE Product (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(99) NOT NULL,
)

CREATE TABLE Inventory (
	StoreId INT NOT NULL FOREIGN KEY REFERENCES Store (Id),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Product (Id),
	Stock INT NOT NULL CHECK (Stock >= 0),
    Price MONEY NOT NULL CHECK (Price > 0),
	PRIMARY KEY (StoreId, ProductId)
)