DROP TABLE IF EXISTS Store
DROP TABLE IF EXISTS Product
DROP TABLE IF EXISTS Inventory


CREATE TABLE Store (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(99) NOT NULL,
    Email NVARCHAR(99) NOT NULL,
    Phone NVARCHAR(99) NOT NULL,
    Addess NVARCHAR(99) NOT NULL
)

CREATE TABLE Product (
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(99) NOT NULL,
	Price MONEY NOT NULL CHECK (Price > 0),
	Description NVARCHAR(999) NULL
)

CREATE TABLE Inventory (
	StoreId INT NOT NULL FOREIGN KEY REFERENCES Store (Id),
	ProductId INT NOT NULL FOREIGN KEY REFERENCES Product (Id),
	Stock INT NOT NULL CHECK (Stock >= 0),
    Markup MONEY NOT NULL CHECK (Markup >= 0),
	PRIMARY KEY (StoreId, ProductId)
)

SELECT * FROM Store
SELECT * FROM Product
SELECT * FROM Inventory
